---
# title: "JAS_DataManagementFor13Tokyo-20250102ver"
# author: "kotdijian"
# date: "17-Jan-2025"
# output:
#   html_document: default
#   word_document: default
# documentclass: bxjsarticle
# classoption: xelatex,ja=standard
# geometry: no
# editor_options:
#   markdown:
#     wrap: 72
---

```{r setup, include=FALSE}
library("knitr")
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale("LC_ALL","Japanese") #Windowsにおけるエンコード問題解決用
```

```{r chunk0, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#パッケージチェックとインストール
if(!require("tidyverse")) install.packages('tidyverse', repos='http://cran.us.r-project.org') 
if(!require("rio")) install.packages('rio', repos='http://cran.us.r-project.org')  
if(!require("formattable")) install.packages('formattable', repos='http://cran.us.r-project.org')  
if(!require("utf8")) install.packages("utf8", repos='http://cran.us.r-project.org')
if(!require("bit64")) install.packages("bit64", repos='http://cran.us.r-project.org')
if(!require("sp")) install.packages("sp", repos='http://cran.us.r-project.org')
if(!require("sf")) install.packages("sf", repos='http://cran.us.r-project.org')
if(!require("stringi")) install.packages("stringi", repos='http://cran.us.r-project.org')

 #パッケージのアクティベート
library("tidyverse")    #下に詳述
library("rio")          #データの読み込み
library("formattable")  #表の表示
library("utf8")         #UTF-8エンコーディング対応
library("bit64")        #UID13桁対応
library("sp")   　      # geospatial point dataframe
library("sf")           # Simple Feature geospatial dataframe
library("stringi")      #文字列変換（ローマ字化）

```　
```{r chunk1, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#変数・データセットのクリア
remove(list=ls())
TokyoTotal <- import("https://github.com/kotdijian/JASOSR/raw/master/13Tokyo/13Tokyo_total.csv", setclass= "tbl_df", encoding = "UTF-8") # TokyoTotalに原データcsvを読み込み、エンコードの指定に注意
```
```{r chunk2, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#データフレームのレコード数(行数)を確認
nrow(TokyoTotal)
```
```{r chunk3, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# データフレームの構造を確認
str(TokyoTotal)
```
```{r chunk4, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#データフレームの先頭数行の内容を表示
head(TokyoTotal)
```
```{r chunk5, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#データフレームの概要・基礎統計量を表示
summary(TokyoTotal) #数値データ列は、最大最小値、第1・第3四分位値、中央・平均値が計算される

```
```{r chunk6, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# 抹消データの削除：前のversion以降の抹消情報をデータセットから削除
Tokyo <- filter(TokyoTotal, SiteName_furigana != "（抹消）")

nrow(Tokyo)
```
```{r chunk7, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# 平面直角座標変換
Tokyo.coord <- drop_na(TokyoTotal,Lon) #経度NAのレコードを除外して新しいオブジェクトに格納

Tokyo.cartesian <- select(Tokyo.coord, Lon, Lat)
Tokyo.cartesian = SpatialPoints(Tokyo.cartesian, proj4string = CRS("+proj=longlat +datum=WGS84"))#spatial point dataframe 変換
Tokyo.cartesian <- spTransform(Tokyo.cartesian, CRS=CRS("+init=epsg:6677")) #WGS84>JGD2011CartIX
Tokyo.cartesian <- as.data.frame(Tokyo.cartesian)  #Spatial point > normal dataframe
Tokyo.cartesian <- rename(Tokyo.cartesian, X = coords.x1, Y = coords.x2)
Tokyo.coord <- cbind(Tokyo.coord,Tokyo.cartesian)
```
```{r chunk8, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#旧石器時代
Tokyo.palaeolithic <- Tokyo %>% 
                      filter(str_detect(Chronology, "旧石器")) %>% 
                      mutate(P = 1)

#縄文時代
Tokyo.jomon <- Tokyo %>% 
                      filter(str_detect(Chronology, "縄文")) %>% 
                      mutate(J = 1)

#弥生時代
Tokyo.yayoi <- Tokyo %>% 
                      filter(str_detect(Chronology, "弥生")) %>% 
                      mutate(Y = 1)

#古墳時代
Tokyo.kofun <- Tokyo %>% 
                      filter(str_detect(Chronology, "古墳")) %>% 
                      mutate(K = 1)

#奈良時代
Tokyo.nara <- Tokyo %>% 
                      filter(str_detect(Chronology, "奈良")) %>% 
                      mutate(N = 1)

#平安時代
Tokyo.heian <- Tokyo %>% 
                      filter(str_detect(Chronology, "平安")) %>% 
                      mutate(H = 1)

#中世
Tokyo.medieval <- Tokyo %>% 
                      filter(str_detect(Chronology, "中世")) %>% 
                      mutate(M = 1)

#近世
Tokyo.earlymodern <- Tokyo %>% 
                      filter(str_detect(Chronology, "近世")) %>% 
                      mutate(E = 1)

#近代
Tokyo.modern <- Tokyo %>% 
                      filter(str_detect(Chronology, "近代")) %>% 
                      mutate(D = 1)

#時代不明
Tokyo.unknown <- Tokyo %>% 
                      filter(str_detect(Chronology, "不明")) %>% 
                      mutate(U = 1)
```
```{r chunk9, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#時代データ追加と統合
    Tokyo.age <- Tokyo %>%
                          dplyr::select(JASID, LGC, Site_no, SiteName_furigana, SiteName_original, Address, Chronology, Lon, Lat) %>%
                          left_join(dplyr::select(Tokyo.palaeolithic, JASID, P),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.jomon, JASID, J),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.yayoi, JASID, Y),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.kofun, JASID, K),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.nara, JASID, N),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.heian, JASID, H),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.medieval, JASID, M),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.earlymodern, JASID, E),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.modern, JASID, D),by = "JASID") %>%
                          left_join(dplyr::select(Tokyo.unknown, JASID, U),by = "JASID") %>%
                          replace_na(list(P = 0, J = 0, Y = 0, K = 0, N = 0, H = 0, M = 0, E = 0, D = 0, U = 0))
```
```{r chunk10, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

```
```{r chunk9, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#全データ書き出し（UTF-8)
write.csv(Tokyo, "13Tokyo.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.age, "13TokyoAge.csv", row.names=FALSE, fileEncoding = "UTF-8")
```
```{r chunk11, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#時代別データ書き出しUTF-8
write.csv(Tokyo.palaeolithic, "byAge/13Tokyo_palaeolithic.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.jomon, "byAge/13Tokyo_jomon.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.yayoi, "byAge/13Tokyo_yayoi.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.kofun, "byAge/13Tokyo_kofun.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.nara, "byAge/13Tokyo_nara.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.heian, "byAge/13Tokyo_heian.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.medieval, "byAge/13Tokyo_medieval.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.earlymodern, "byAge/13Tokyo_earlymodern.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.modern, "byAge/13Tokyo_modern.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Tokyo.unknown, "byAge/13Tokyo_unknown.csv", row.names=FALSE, fileEncoding = "UTF-8")
```
```{r chunk11, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
write.csv(Tokyo.coord, "SJS/13Tokyo_totalCoordSJS.csv", row.names = FALSE, fileEncoding = "CP932")　#Shift-JIS書き出し, ファイル名を適宜指定(全レコード)

#時代別データ書き出し
Tokyo.palaeolithic <- drop_na(Tokyo.palaeolithic,Lon)
write.csv(Tokyo.palaeolithic, "SJS/13Tokyo_palaeolithicSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.jomon <- drop_na(Tokyo.jomon,Lon)
write.csv(Tokyo.jomon, "SJS/13Tokyo_jomonSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.yayoi<- drop_na(Tokyo.yayoi,Lon)
write.csv(Tokyo.yayoi, "SJS/13Tokyo_yayoiSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.kofun <- drop_na(Tokyo.kofun,Lon)
write.csv(Tokyo.kofun, "SJS/13Tokyo_kofunSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.nara <- drop_na(Tokyo.nara,Lon)
write.csv(Tokyo.nara, "SJS/13Tokyo_naraSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.heian <- drop_na(Tokyo.heian,Lon)
write.csv(Tokyo.heian, "SJS/13Tokyo_heianSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.medieval <- drop_na(Tokyo.medieval,Lon)
write.csv(Tokyo.medieval, "SJS/13Tokyo_medievalSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.earlymodern <- drop_na(Tokyo.earlymodern,Lon)
write.csv(Tokyo.earlymodern, "SJS/13Tokyo_earlymodernSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.modern <- drop_na(Tokyo.modern,Lon)
write.csv(Tokyo.earlymodern, "SJS/13Tokyo_modernSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Tokyo.unknown <- drop_na(Tokyo.unknown,Lon)
write.csv(Tokyo.unknown, "SJS/13Tokyo_unknownSJS.csv", row.names=FALSE, fileEncoding = "CP932")

```
```{r chunk12, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#集計1:自治体別合計
Tokyo.summary1 <- Tokyo %>%  
  group_by(LGC) %>%  #LGCで集約
  count %>%                   #レコード数=遺跡数をカウント
  rename(Sum = n) %>%  #集計結果が格納される列の名前をn→遺跡数合計に変更
  arrange(LGC)       #LGCで昇順に並び替え
```
```{r chunk13, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#集計2:時代別
　  # 旧石器
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, P)　%>%
    filter(P != 0) %>%
    count %>%
    ungroup %>%
    dplyr::select(-P) %>%
    rename(P = n)

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 縄文
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, J)　%>%
    filter(J != 0) %>%
    count %>% 
    ungroup %>%
    dplyr::select(-J) %>%
    rename(J = n)

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 弥生
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, Y)　%>%
    filter(Y != 0) %>%
    count %>% 
    ungroup %>%
    dplyr::select(-Y) %>%
    rename(Y = n)

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 古墳
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, K)　%>%
    filter(K != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-K) %>%
    rename(K = n)

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 奈良
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, N)　%>%
    filter(N != 0) %>% 
    count %>%
    ungroup %>%
    dplyr::select(-N) %>%
    rename(N = n) 
    
  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 平安
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, H)　%>%
    filter(H != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-H) %>%
    rename(H = n)
    

 Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 中世
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, M)　%>%
    filter(M != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-M) %>%
    rename(M = n) 

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 近世
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, E)　%>%
    filter(E != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-E) %>%
    rename(E = n) 

 Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 近代
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, D)　%>%
    filter(D != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-D) %>%
    rename(D = n) 

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # 時代不明
  Tokyo.summary2 <- Tokyo.age %>% 
    group_by(LGC, U)　%>%
    filter(U != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-U) %>%
    rename(U = n)

  Tokyo.summary1 <- left_join(Tokyo.summary1, Tokyo.summary2, by = "LGC")

  # NAを0に置換
  Tokyo.summary1[is.na(Tokyo.summary1)] <- 0

  # 合計を計算・結合
　Tokyo.sum <- colSums(Tokyo.summary1)
  Tokyo.sum$LGC <- 13000
  Tokyo.summary1 <- rbind(Tokyo.summary1, Tokyo.sum)
  #区部集計
  Tokyo.sum <- Tokyo.summary1 %>%
    group_by(LGC) %>%
    filter(LGC <13200) %>%
    filter(LGC != 13000) %>%
    colSums
  Tokyo.sum$LGC <- 13100
  Tokyo.summary1 <- rbind(Tokyo.summary1, Tokyo.sum)
  rm(Tokyo.sum)

  #多摩地区集計
  Tokyo.sum <- Tokyo.summary1 %>%
    group_by(LGC) %>%
    filter(LGC >13200 & LGC <13260) %>%
    colSums
  Tokyo.sum$LGC <- 13200
  Tokyo.summary1 <- rbind(Tokyo.summary1, Tokyo.sum)
  # 一時保管オブジェクトを削除
  rm(Tokyo.sum)
  rm(Tokyo.summary2)

#区市町村名追加
  #自治体名の読み込み(more human readable)
  LGC <- import("https://github.com/kotdijian/JASOSR/raw/master/13Tokyo/LGC_13Tokyo.csv", setclass= "tbl_df", encoding ="UTF-8" ) #LGC_13Tokyo.csv=東京都LGCリスト
  # LGC <- rename(LGC,区市町村名 = 名称)

  #LGCでつないで区市町村名を追加
  Tokyo.summary1 <- Tokyo.summary1 %>%
                          left_join(dplyr::select(LGC,LGC,Name), by = "LGC") %>%
                          dplyr::select(LGC, Name, Sum, P, J, Y, K, N, H, M, E, D, U) #列名の並べ替え
                          
# .csv保存
write.csv(Tokyo.summary1, "13TokyoSummary1.csv", row.names = FALSE, fileEncoding = "UTF-8")
```