---
# title: "JAS_DataManagementFor14130Saitama-20250102ver"
# author: "kotdijian"
# date: "02-Jan-2025"
# output:
#   html_document: default
#   word_document: default
# documentclass: bxjsarticle
# classoption: xelatex,ja=standard
# geometry: no
# editor_options:
#   markdown:
#     wrap: 72
---

```{r setup, include=FALSE}
library("knitr")
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale("LC_ALL","Japanese") #Windowsにおけるエンコード問題解決用
```

```{r chunk0, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#パッケージチェックとインストール
if(!require("tidyverse")) install.packages('tidyverse', repos='http://cran.us.r-project.org') 
if(!require("rio")) install.packages('rio', repos='http://cran.us.r-project.org')  
if(!require("formattable")) install.packages('formattable', repos='http://cran.us.r-project.org')  
if(!require("utf8")) install.packages("utf8", repos='http://cran.us.r-project.org')
if(!require("bit64")) install.packages("bit64", repos='http://cran.us.r-project.org')

 #パッケージのアクティベート
library("tidyverse")    #下に詳述
library("rio")          #データの読み込み
library("formattable")  #表の表示
library("utf8")         #UTF-8エンコーディング対応
library("bit64")        #UID13桁対応
```
```{r chunk1, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
SaitamaTotal <- import("https://github.com/kotdijian/JASOSR/raw/master/11Saitama/11Saitama_total.csv", setclass= "tbl_df", encoding = "UTF-8") # SaitamaTotalに原データcsvを読み込み、エンコードの指定に注意
```
```{r chunk2, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#データフレームのレコード数(行数)を確認
nrow(SaitamaTotal)
```
```{r chunk3, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# データフレームの構造を確認
str(SaitamaTotal)
```
```{r chunk4, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#データフレームの先頭数行の内容を表示
head(SaitamaTotal)
```

```{r chunk5, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#データフレームの概要・基礎統計量を表示
summary(SaitamaTotal) #数値データ列は、最大最小値、第1・第3四分位値、中央・平均値が計算される

```
```{r chunk6, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# 抹消データの削除：前のversion以降の抹消情報をデータセットから削除
Saitama <- filter(SaitamaTotal, 備考 != "抹消")
Saitama.medieval <- dplyr::select(SaitamaTotal,"JASID","鎌倉","南北朝","室町","戦国") #中世の集計
Saitama.medieval <- Saitama.medieval %>%
  replace_na(list(鎌倉=0,南北朝=0,室町=0,戦国=0)) %>%
  rowwise() %>%
  mutate(M = sum(c_across()))
  Saitama.medieval$M <- as.numeric (Saitama.medieval$M > Saitama.medieval$JASID)

Saitama <- SaitamaTotal %>%
              rename("自治体コード"="LGC","P"="旧石器","J"="縄文","Y"="弥生","K"="古墳","N"="奈良","H"="平安","E"="江戸","D"="近代","U"="不明") %>%
              left_join(dplyr::select(Saitama.medieval, JASID, M),by = "JASID") %>%
              replace_na(list(P=0,J=0,Y=0,K=0,N=0,H=0,E=0,U=0))

#自治体名称追加
  #自治体名の読み込み(more human readable)
  LGC <- import("https://github.com/kotdijian/JASOSR/raw/master/11Saitama/LGC_11Saitama.csv", setclass= "tbl_df", encoding ="UTF-8" ) #LGC_11Saitama.csv=埼玉県自治体コードリスト
  LGC <- rename(LGC,区市町村名 = 名称)

  #自治体コードでつないで区市町村名を追加
  Saitama <- Saitama %>%
              left_join(dplyr::select(LGC,自治体コード,区市町村名), by = "自治体コード") %>%
              dplyr::select(JASID, 自治体コード, 区市町村名, 遺跡番号, 遺跡名, 種別, 緯度, 経度,P,J,Y,K,N,H,M,E,D,U) %>%
              arrange(JASID)
```

```{r chunk7, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

#旧石器時代
Saitama.palaeolithic <- Saitama %>% 
                      filter(P == 1)

#縄文時代
Saitama.jomon <- Saitama %>% 
                      filter(J == 1)

#弥生時代
Saitama.yayoi <- Saitama %>% 
                      filter(Y == 1)

#古墳時代
Saitama.kofun <- Saitama %>% 
                      filter(K == 1)

#奈良時代
Saitama.nara <- Saitama %>% 
                      filter(N == 1)

#平安時代
Saitama.heian <- Saitama %>% 
                      filter(H == 1)

#中世
Saitama.medieval <- Saitama %>% 
                      filter(M == 1)

#近世
Saitama.earlymodern <- Saitama %>% 
                      filter(E == 1)

#近代
Saitama.modern <- Saitama %>% 
                      filter(D == 1)

#時代不明
Saitama.unknown <- Saitama %>% 
                      filter(U == 1)
```
```{r chunk9, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#全データ書き出し（UTF-8)
write.csv(Saitama, "11Saitama.csv", row.names=FALSE, fileEncoding = "UTF-8")
```
```{r chunk10, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#時代別データ書き出しUTF-8
write.csv(Saitama.palaeolithic, "byAge/11Saitama_palaeolithic.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.jomon, "byAge/11Saitama_jomon.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.yayoi, "byAge/11Saitama_yayoi.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.kofun, "byAge/11Saitama_kofun.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.nara, "byAge/11Saitama_nara.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.heian, "byAge/11Saitama_heian.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.medieval, "byAge/11Saitama_medieval.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.earlymodern, "byAge/11Saitama_earlymodern.csv", row.names=FALSE, fileEncoding = "UTF-8")
# write.csv(Saitama.modern, "byAge/11Saitama_modern.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(Saitama.unknown, "byAge/11Saitama_unknown.csv", row.names=FALSE, fileEncoding = "UTF-8")
```
```{r chunk11, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
Saitama.coord <- drop_na(SaitamaTotal,経度) #経度NAのレコードを除外して新しいオブジェクトに格納
write.csv(Saitama.coord, "SJS/11Saitama_totalCoordSJS.csv", row.names = FALSE, fileEncoding = "CP932")　#Shift-JIS書き出し, ファイル名を適宜指定(全レコード)

#時代別データ書き出し
Saitama.palaeolithic <- drop_na(Saitama.palaeolithic,経度)
write.csv(Saitama.palaeolithic, "SJS/11Saitama_palaeolithicSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.jomon <- drop_na(Saitama.jomon,経度)
write.csv(Saitama.jomon, "SJS/11Saitama_jomonSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.yayoi<- drop_na(Saitama.yayoi,経度)
write.csv(Saitama.yayoi, "SJS/11Saitama_yayoiSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.kofun <- drop_na(Saitama.kofun,経度)
write.csv(Saitama.kofun, "SJS/11Saitama_kofunSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.nara <- drop_na(Saitama.nara,経度)
write.csv(Saitama.nara, "SJS/11Saitama_naraSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.heian <- drop_na(Saitama.heian,経度)
write.csv(Saitama.heian, "SJS/11Saitama_heianSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.medieval <- drop_na(Saitama.medieval,経度)
write.csv(Saitama.medieval, "SJS/11Saitama_medievalSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.earlymodern <- drop_na(Saitama.earlymodern,経度)
write.csv(Saitama.earlymodern, "SJS/11Saitama_earlymodernSJS.csv", row.names=FALSE, fileEncoding = "CP932")

#Saitama.modern <- drop_na(Saitama.modern,経度)
#write.csv(Saitama.earlymodern, "SJS/11Saitama_modernSJS.csv", row.names=FALSE, fileEncoding = "CP932")

Saitama.unknown <- drop_na(Saitama.unknown,経度)
write.csv(Saitama.unknown, "SJS/11Saitama_unknownSJS.csv", row.names=FALSE, fileEncoding = "CP932")

```
```{r chunk12, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#集計1:自治体別合計
Saitama.summary1 <- Saitama %>%  
  group_by(自治体コード) %>%  #自治体コードで集約
  count %>%                   #レコード数=遺跡数をカウント
  rename(遺跡数合計 = n) %>%  #集計結果が格納される列の名前をn→遺跡数合計に変更
  arrange(自治体コード)       #自治体コードで昇順に並び替え
```
```{r chunk13, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
#集計2:時代別
　  # 旧石器
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, P)　%>%
    filter(P != 0) %>%
    count %>%
    ungroup %>%
    dplyr::select(-P) %>%
    rename("P" = "n")

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 縄文
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, J)　%>%
    filter(J != 0) %>%
    count %>% 
    ungroup %>%
    dplyr::select(-J) %>%
    rename("J" = "n")

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 弥生
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, Y)　%>%
    filter(Y != 0) %>%
    count %>% 
    ungroup %>%
    dplyr::select(-Y) %>%
    rename("Y" = "n") 

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 古墳
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, K)　%>%
    filter(K != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-K) %>% 
    rename("K" = "n")

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 奈良
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, N)　%>%
    filter(N != 0) %>% 
    count %>%
    ungroup %>%
    dplyr::select(-N) %>% 
    rename("N" = "n")

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 平安
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, H)　%>%
    filter(H != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-H) %>% 
    rename("H" = "n")

 Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 中世
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, M)　%>%
    filter(M != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-M) %>%
    rename("M" = "n") 

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 近世
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, E)　%>%
    filter(E != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-E) %>%
    rename("E" = "n") 

 Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 近代
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, D)　%>%
    filter(D != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-D) %>%
    rename("D" = "n") 

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # 時代不明
  Saitama.summary2 <- Saitama %>% 
    group_by(自治体コード, U)　%>%
    filter(U != 0) %>%
    count %>% 
    ungroup %>% 
    dplyr::select(-U) %>%
    rename("U" = "n")

  Saitama.summary1 <- left_join(Saitama.summary1, Saitama.summary2, by = "自治体コード")

  # NAを0に置換
  Saitama.summary1[is.na(Saitama.summary1)] <- 0

  # 合計を計算・結合
　Saitama.sum <- colSums(Saitama.summary1)
  Saitama.sum$自治体コード <- 11000
  Saitama.summary1 <- rbind(Saitama.summary1, Saitama.sum)
  
  #自治体コードでつないで区市町村名を追加
  Saitama.summary1 <- Saitama.summary1 %>%
                        left_join(dplyr::select(LGC,自治体コード,区市町村名), by = "自治体コード") %>%
                        dplyr::select(自治体コード, 区市町村名, 遺跡数合計,P,J,Y,K,N,H,M,E,D,U)
  
  # 一時保管オブジェクトを削除
  rm(Saitama.sum)
  rm(Saitama.summary2)

# .csv保存
write.csv(Saitama.summary1, "13SaitamaSummary1.csv", row.names = FALSE, fileEncoding = "UTF-8")
```